# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qaQmOIoC2XHt8iDXFScwrm_qJq-Ffs9_
"""

name = input("Enter Your Name:")

weight = float(input("Enter your weight in pounds:"))

height = int(input("Enter your height in inches:"))

BMI = (weight * 703) / (height * height)

print(BMI)

if BMI >0:
  if (BMI<18.5):
    print(name +" ,You are underweight:")
  elif (BMI<=24.9):
    print(name +" ,You are normal weight:")
  elif (BMI < 29.9):
    print(name +" ,You are overweight:")
  elif (BMI < 34.9):
    print(name +" ,You are obese:")
  elif (BMI < 39.9):
    print(name +" ,You are severely obese:")
  else:
    print("You are modibly obese")
else:
  print("Enter Valid Inputs:")

if BMI >0:
  if (BMI<18.5):
    print(name +" ,You are underweight:")
  elif (BMI<=24.9):
    print(name +" ,You are normal weight:")
  elif (BMI < 29.9):
    print(name +" ,You are overweight:")
  elif (BMI < 34.9):
    print(name +" ,You are obese:")
  elif (BMI < 39.9):
    print(name +" ,You are severely obese:")
  else:
    print("You are modibly obese")
else:
  print("Enter Valid Inputs:")